package io.github.pedrogush.cardfscan.core.match

import io.github.pedrogush.cardfscan.core.TestPaths
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.doubleOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.jupiter.api.Assumptions.assumeTrue
import org.junit.jupiter.api.DynamicTest
import org.junit.jupiter.api.TestFactory
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals

/** Runs every vector of testdata/names/match_cases.json (generated by tools/reference_match.py). */
class MatchCasesTest {
    private val casesFile = File(TestPaths.namesDir, "match_cases.json")

    // @TestFactory makes one JUnit test per JSON case, so failures name the exact input.
    @TestFactory
    fun matchCases(): List<DynamicTest> {
        assumeTrue(casesFile.exists(), "match_cases.json not available")
        val cases = Json.parseToJsonElement(casesFile.readText()).jsonObject["cases"]!!.jsonArray
        val index = TestPaths.nameIndex
        return cases.map { it.jsonObject }.map { case ->
            val raw = case.str("raw")!!
            DynamicTest.dynamicTest("${case.str("note")}: '$raw'") {
                val r = index.match(raw)
                assertEquals(case.str("cleaned"), r.cleaned, "cleaned")
                assertEquals(case.str("key"), r.key, "key")
                assertEquals(case.str("status"), r.status.name.lowercase(), "status")
                case.num("best_score")?.let { assertEquals(it, r.best!!.score, 0.01, "best_score") }
                case.num("runner_up_score")?.let { assertEquals(it, r.runnerUpScore, 0.01, "runner_up_score") }
                case.str("best_oracle_id")?.let { assertEquals(it, r.best!!.oracleId, "best_oracle_id") }
                if (r.status == SlotStatus.AUTO) {
                    assertEquals(case.str("oracle_id"), r.best!!.oracleId, "oracle_id")
                    assertEquals(case.str("name"), r.best!!.name, "name")
                    assertEquals(case.str("lang"), r.best!!.lang, "lang")
                }
            }
        }
    }

    @Test
    fun ratioMatchesRapidfuzzExamples() {
        // Values from rapidfuzz.fuzz.ratio.
        assertEquals(100f, IndelPattern.ratio("abc", "abc"))
        assertEquals(0f, IndelPattern.ratio("abc", "xyz"))
        assertEquals(2f * 3 / 7 * 100, IndelPattern.ratio("abcd", "abd"), 1e-4f)
        // One substitution = one delete + one insert: LCS 13 of 14 + 14 chars.
        assertEquals(100f * 26 / 28, IndelPattern.ratio("lightning bolt", "lightnimg bolt"), 1e-4f)
    }

    @Test
    fun longPatternsUseMultiWordPath() {
        val a = "a".repeat(70) + " bolt " + "z".repeat(30)
        val b = "a".repeat(69) + " boltz " + "z".repeat(29)
        // Reference: plain O(n*m) dynamic programme.
        assertEquals(dpRatio(a, b), IndelPattern.ratio(a, b), 1e-4f)
        assertEquals(dpRatio(b, a), IndelPattern.ratio(b, a), 1e-4f)
    }

    @Test
    fun normalizeExamples() {
        assertEquals("relampago", TextNormalizer.normalize("Relâmpago"))
        assertEquals("anulacao", TextNormalizer.normalize("Anulação"))
        assertEquals("will o the wisp", TextNormalizer.normalize("Will-o'-the-Wisp"))
        assertEquals("fire ice", TextNormalizer.normalize("Fire // Ice"))
        assertEquals("Lightning Bolt {R", TextNormalizer.clean("Lightning Bolt {R}"))
        assertEquals("Serra Angel", TextNormalizer.clean("Serra Angel 3 @@"))
    }

    private fun dpRatio(a: String, b: String): Float {
        val dp = Array(a.length + 1) { IntArray(b.length + 1) }
        for (i in 1..a.length) for (j in 1..b.length) {
            dp[i][j] = if (a[i - 1] == b[j - 1]) dp[i - 1][j - 1] + 1 else maxOf(dp[i - 1][j], dp[i][j - 1])
        }
        val lenSum = a.length + b.length
        return (100.0 * 2 * dp[a.length][b.length] / lenSum).toFloat()
    }

    // Extension functions: add small helpers to an existing type (here JsonObject) without subclassing.
    private fun JsonObject.str(k: String): String? = (this[k] as? JsonPrimitive)?.contentOrNull
    private fun JsonObject.num(k: String): Double? = (this[k] as? JsonPrimitive)?.doubleOrNull
}

class SpaceGuardTest {
    @Test
    fun droppedSpaceBetweenTwoRealNamesIsNotTrusted() {
        val index = io.github.pedrogush.cardfscan.core.TestPaths.nameIndex
        // "Waste Land" (Un-card) read without its space matches "Wasteland" exactly.
        val r = index.match("WasteLand")
        assertEquals(SlotStatus.AUTO, r.status)
        assertEquals(false, index.isRobustToSpaces(r))
        // An ordinary name is unaffected.
        assertEquals(true, index.isRobustToSpaces(index.match("Lightning Bolt")))
    }
}
